version: '3'
services:
  db:
    image: redis:6
  backend:
    image: ksisu/tell-me-a-secret
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      CYPTOR_SECRET: '4AmEdqF7YTruR2o4^2BfwkSA0weHtEVgHzo7Rqy'
    ports:
      - 8080:8080
  web:
    build:
      context: .
    environment:
      BASE_URL: http://localhost
      API_URL: http://localhost:8080/api
    ports:
      - 80:80
